// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSalon.Models.EntityModels
{
    /// <summary>
    /// 代碼類型實體
    /// </summary>
    public partial class CodeType
    {
        /// <summary>
        /// 代碼類型唯一識別碼
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// 代碼類型代碼
        /// </summary>
        public string CodeType1 { get; set; }

        /// <summary>
        /// 代碼類型名稱
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// 描述說明
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// 建立者
        /// </summary>
        public string CreateUser { get; set; }

        /// <summary>
        /// 建立時間
        /// </summary>
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 修改者
        /// </summary>
        public string ModifyUser { get; set; }

        /// <summary>
        /// 修改時間
        /// </summary>
        public DateTime ModifyTime { get; set; }
    }
}
