// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSalon.Models.EntityModels
{
    public partial class ContactPerson
    {
        public ContactPerson()
        {
            NotificationLog = new HashSet<NotificationLog>();
            PetRelation = new HashSet<PetRelation>();
        }

        public long ContactPersonId { get; set; }
        /// <summary>
        /// 名字
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 暱稱
        /// </summary>
        public string NickName { get; set; }
        /// <summary>
        /// 連絡電話
        /// </summary>
        public string ContactNumber { get; set; }
        public string CreateUser { get; set; }
        public DateTime CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public DateTime ModifyTime { get; set; }

        public virtual ICollection<NotificationLog> NotificationLog { get; set; }
        public virtual ICollection<PetRelation> PetRelation { get; set; }
    }
}