// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSalon.Models.EntityModels
{
    public partial class PaymentRecord
    {
        public long PaymentRecordId { get; set; }
        public int? PaymentCode { get; set; }
        public long? PetId { get; set; }
        public long? SubscriptionId { get; set; }
        public long? ReserveRecordId { get; set; }
        public string PaymentType { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentStatus { get; set; }
        public DateTime PaymentDate { get; set; }
        public string TransactionReference { get; set; }
        public decimal? ReceivablePrice { get; set; }
        public decimal? ActualPrice { get; set; }
        public string Notes { get; set; }
        public string CreateUser { get; set; }
        public DateTime CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public DateTime ModifyTime { get; set; }

        public virtual Pet Pet { get; set; }
        public virtual Subscription Subscription { get; set; }
        public virtual ReserveRecord ReserveRecord { get; set; }
    }
}