// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using PetSalon.Models;

namespace PetSalon.Models.EntityModels
{
    /// <summary>
    /// 預約服務明細 - 記錄每個預約包含的具體服務項目及價格
    /// </summary>
    public partial class ReservationService : IEntity
    {
        /// <summary>
        /// 預約服務明細唯一識別碼
        /// </summary>
        public long ReservationServiceId { get; set; }

        /// <summary>
        /// 預約記錄ID，關聯至ReserveRecord表
        /// </summary>
        public long ReserveRecordId { get; set; }

        /// <summary>
        /// 服務項目ID，關聯至Service表
        /// </summary>
        public long ServiceId { get; set; }

        /// <summary>
        /// 服務價格
        /// </summary>
        public decimal ServicePrice { get; set; }

        /// <summary>
        /// 服務時長（分鐘）
        /// </summary>
        public int Duration { get; set; }

        /// <summary>
        /// 備註說明
        /// </summary>
        public string Notes { get; set; }

        public string CreateUser { get; set; }
        public DateTime CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public DateTime ModifyTime { get; set; }

        public virtual ReserveRecord ReserveRecord { get; set; }
        public virtual Service Service { get; set; }
    }
}