// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using PetSalon.Models;

namespace PetSalon.Models.EntityModels
{
    /// <summary>
    /// 預約紀錄明細表 - 存放寵物美容預約記錄的明細資訊
    /// </summary>
    public partial class ReserveRecordDetail : IEntity
    {
        /// <summary>
        /// 預約記錄明細唯一識別碼
        /// </summary>
        public long ReserveRecordDetailId { get; set; }

        /// <summary>
        /// 預約記錄識別碼，關聯至 ReserveRecord 表
        /// </summary>
        public long ReserveRecordId { get; set; }

        /// <summary>
        /// 服務類型
        /// </summary>
        public string ServiceType { get; set; }

        /// <summary>
        /// 服務價格
        /// </summary>
        public decimal Price { get; set; }

        /// <summary>
        /// 建立者
        /// </summary>
        public string CreateUser { get; set; }

        /// <summary>
        /// 建立時間
        /// </summary>
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 修改者
        /// </summary>
        public string ModifyUser { get; set; }

        /// <summary>
        /// 修改時間
        /// </summary>
        public DateTime ModifyTime { get; set; }

        /// <summary>
        /// 導航屬性：關聯的預約記錄
        /// </summary>
        public virtual ReserveRecord ReserveRecord { get; set; }
    }
}
