// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace PetSalon.Models.EntityModels
{
    public partial class Scpermission
    {
        public Scpermission()
        {
            ScrolePermissions = new HashSet<ScrolePermission>();
        }

        public long PermissionId { get; set; }
        public string PermissionCode { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }

        public virtual ICollection<ScrolePermission> ScrolePermissions { get; set; }
    }
}
