// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace PetSalon.Models.EntityModels
{
    public partial class ScrolePermission
    {
        public long RolePermissionId { get; set; }
        public long RoleId { get; set; }
        public long PermissionId { get; set; }

        public virtual Scrole Role { get; set; }
        public virtual Scpermission Permission { get; set; }
    }
}
