// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace PetSalon.Models.EntityModels
{
    public partial class ScuserRole
    {
        public long UserRoleId { get; set; }
        public long ScuserId { get; set; }
        public long RoleId { get; set; }

        public virtual Scrole Role { get; set; }
        public virtual Scuser Scuser { get; set; }
    }
}
