// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSalon.Models.EntityModels
{
    public partial class Scuser
    {
        public long ScuserId { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public DateTime? LastLogin { get; set; }
        public string CreateUser { get; set; }
        public DateTime CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public DateTime ModifyTime { get; set; }
    }
}