// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using PetSalon.Models;

namespace PetSalon.Models.EntityModels
{
    /// <summary>
    /// 服務項目管理 - 存放寵物美容的各種服務項目，包含價格、時長等資訊
    /// </summary>
    public partial class Service : IEntity
    {
        public Service()
        {
            PetServicePrice = new HashSet<PetServicePrice>();
            ReservationService = new HashSet<ReservationService>();
        }

        /// <summary>
        /// 服務項目唯一識別碼
        /// </summary>
        public long ServiceId { get; set; }

        /// <summary>
        /// 服務項目名稱
        /// </summary>
        public string ServiceName { get; set; }

        /// <summary>
        /// 服務類型，關聯至SystemCode
        /// </summary>
        public string ServiceType { get; set; }

        /// <summary>
        /// 基礎價格
        /// </summary>
        public decimal BasePrice { get; set; }

        /// <summary>
        /// 服務時長（分鐘）
        /// </summary>
        public int Duration { get; set; }

        /// <summary>
        /// 服務描述
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// 是否啟用
        /// </summary>
        public bool IsActive { get; set; }

        /// <summary>
        /// 顯示排序
        /// </summary>
        public int Sort { get; set; }

        public string CreateUser { get; set; }
        public DateTime CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public DateTime ModifyTime { get; set; }

        public virtual ICollection<PetServicePrice> PetServicePrice { get; set; }
        public virtual ICollection<ReservationService> ReservationService { get; set; }
    }
}