// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSalon.Models.EntityModels
{
    public partial class Subscription
    {
        public Subscription()
        {
            ReserveRecord = new HashSet<ReserveRecord>();
            PaymentRecord = new HashSet<PaymentRecord>();
            NotificationLog = new HashSet<NotificationLog>();
        }

        public long SubscriptionId { get; set; }
        public long PetId { get; set; }
        public DateTime SubscriptionDate { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string SubscriptionType { get; set; }
        public long? SubscriptionTypeId { get; set; }
        public int TotalUsageLimit { get; set; }
        public int UsedCount { get; set; }
        public int ReservedCount { get; set; }
        public decimal SubscriptionPrice { get; set; }
        public string Notes { get; set; }
        public string CreateUser { get; set; }
        public DateTime CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public DateTime ModifyTime { get; set; }

        public virtual Pet Pet { get; set; }
        public virtual SubscriptionType SubscriptionTypeNavigation { get; set; }
        public virtual ICollection<ReserveRecord> ReserveRecord { get; set; }
        public virtual ICollection<PaymentRecord> PaymentRecord { get; set; }
        public virtual ICollection<NotificationLog> NotificationLog { get; set; }
    }
}