CREATE TABLE [dbo].[Income](
	[IncomeID] [bigint] IDENTITY(1,1) NOT NULL,
	[ReserveRecordID] [bigint] NULL, -- Link to reservation if applicable
	[IncomeType] [varchar](100) NOT NULL, -- Links to SystemCode
	[Amount] [money] NOT NULL,
	[IncomeDate] [date] NOT NULL,
	[Description] [nvarchar](500) NULL,
	[IsAutoGenerated] [bit] NOT NULL DEFAULT(0), -- True if generated from reservation completion
	[CreateUser] [nvarchar](20) NOT NULL,
	[CreateTime] [datetime] NOT NULL DEFAULT(GETDATE()),
	[ModifyUser] [nvarchar](20) NOT NULL,
	[ModifyTime] [datetime] NOT NULL DEFAULT(GETDATE()),
 CONSTRAINT [PK_Income] PRIMARY KEY CLUSTERED 
(
	[IncomeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [FK_Income_ReserveRecord] FOREIGN KEY([ReserveRecordID])
REFERENCES [dbo].[ReserveRecord] ([ReserveRecordID])
) ON [PRIMARY]
GO