// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSalon.Models.EntityModels
{
    public partial class NotificationLog
    {
        public long NotificationLogId { get; set; }
        public string NotificationType { get; set; }
        public string RecipientType { get; set; }
        public long? RecipientId { get; set; }
        public long? RelatedPetId { get; set; }
        public long? RelatedSubscriptionId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string SendMethod { get; set; }
        public string SendStatus { get; set; }
        public DateTime ScheduledTime { get; set; }
        public DateTime? SentTime { get; set; }
        public string ErrorMessage { get; set; }
        public string CreateUser { get; set; }
        public DateTime CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public DateTime ModifyTime { get; set; }

        public virtual ContactPerson Recipient { get; set; }
        public virtual Pet RelatedPet { get; set; }
        public virtual Subscription RelatedSubscription { get; set; }
    }
}