// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using PetSalon.Models;

namespace PetSalon.Models.EntityModels
{
    public partial class Pet : IEntity
    {
        public Pet()
        {
            NotificationLog = new HashSet<NotificationLog>();
            PaymentRecord = new HashSet<PaymentRecord>();
            PetRelation = new HashSet<PetRelation>();
            ReserveRecord = new HashSet<ReserveRecord>();
            Subscription = new HashSet<Subscription>();
            PetServiceDuration = new HashSet<PetServiceDuration>();
            PetServicePrice = new HashSet<PetServicePrice>();
        }

        public long PetId { get; set; }
        /// <summary>
        /// 名字
        /// </summary>
        public string PetName { get; set; }
        /// <summary>
        /// 性別
        /// </summary>
        public string Gender { get; set; }
        /// <summary>
        /// 品種
        /// </summary>
        public string Breed { get; set; }
        /// <summary>
        /// 生日
        /// </summary>
        public DateTime? BirthDay { get; set; }
        /// <summary>
        /// 單次價格
        /// </summary>
        public decimal? NormalPrice { get; set; }
        /// <summary>
        /// 包月價格
        /// </summary>
        public decimal? SubscriptionPrice { get; set; }
        public string CreateUser { get; set; }
        public DateTime CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public DateTime ModifyTime { get; set; }

        public virtual ICollection<NotificationLog> NotificationLog { get; set; }
        public virtual ICollection<PaymentRecord> PaymentRecord { get; set; }
        public virtual ICollection<PetRelation> PetRelation { get; set; }
        public virtual ICollection<ReserveRecord> ReserveRecord { get; set; }
        public virtual ICollection<Subscription> Subscription { get; set; }
        public virtual ICollection<PetServiceDuration> PetServiceDuration { get; set; }
        public virtual ICollection<PetServicePrice> PetServicePrice { get; set; }
    }
}