// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSalon.Models.EntityModels
{
    public partial class PetRelation
    {
        public long PetRelationId { get; set; }
        public long PetId { get; set; }
        public long ContactPersonId { get; set; }
        public string RelationshipType { get; set; }
        public int Sort { get; set; }
        public string CreateUser { get; set; }
        public DateTime CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public DateTime ModifyTime { get; set; }

        public virtual ContactPerson ContactPerson { get; set; }
        public virtual Pet Pet { get; set; }
    }
}