// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using PetSalon.Models;

namespace PetSalon.Models.EntityModels
{
    /// <summary>
    /// 寵物服務客製化價格 - 為特定寵物設定不同的服務價格和時長
    /// </summary>
    public partial class PetServicePrice : IEntity
    {
        /// <summary>
        /// 寵物服務價格唯一識別碼
        /// </summary>
        public long PetServicePriceId { get; set; }

        /// <summary>
        /// 寵物ID，關聯至Pet表
        /// </summary>
        public long PetId { get; set; }

        /// <summary>
        /// 服務項目ID，關聯至Service表
        /// </summary>
        public long ServiceId { get; set; }

        /// <summary>
        /// 客製化價格，覆蓋服務預設價格
        /// </summary>
        public decimal? CustomPrice { get; set; }

        /// <summary>
        /// 客製化時長，覆蓋服務預設時長
        /// </summary>
        public int? Duration { get; set; }

        /// <summary>
        /// 備註說明
        /// </summary>
        public string Notes { get; set; }

        /// <summary>
        /// 是否啟用
        /// </summary>
        public bool IsActive { get; set; }

        public string CreateUser { get; set; }
        public DateTime CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public DateTime ModifyTime { get; set; }

        public virtual Pet Pet { get; set; }
        public virtual Service Service { get; set; }
    }
}