// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace PetSalon.Models.EntityModels
{
    public partial class PetSalonContext : DbContext
    {
        public PetSalonContext()
        {
        }

        public PetSalonContext(DbContextOptions<PetSalonContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ContactPerson> ContactPerson { get; set; }
        public virtual DbSet<PaymentRecord> PaymentRecord { get; set; }
        public virtual DbSet<Pet> Pet { get; set; }
        public virtual DbSet<PetRelation> PetRelation { get; set; }
        public virtual DbSet<ReserveRecord> ReserveRecord { get; set; }
        public virtual DbSet<Scrole> Scrole { get; set; }
        public virtual DbSet<Scuser> Scuser { get; set; }
        public virtual DbSet<Subscription> Subscription { get; set; }
        public virtual DbSet<SystemCode> SystemCode { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ContactPerson>(entity =>
            {
                entity.Property(e => e.ContactPersonId).HasColumnName("ContactPersonID");

                entity.Property(e => e.ContactNumber)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasComment("連絡電話");

                entity.Property(e => e.CreateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.CreateUser)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.ModifyTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ModifyUser)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasComment("名字");

                entity.Property(e => e.NickName)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasComment("暱稱");
            });

            modelBuilder.Entity<PaymentRecord>(entity =>
            {
                entity.Property(e => e.PaymentRecordId).HasColumnName("PaymentRecordID");

                entity.Property(e => e.ActualPrice).HasColumnType("money");

                entity.Property(e => e.CreateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.CreateUser)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.ModifyTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ModifyUser)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.PetId).HasColumnName("PetID");

                entity.Property(e => e.ReceivablePrice).HasColumnType("money");

                entity.HasOne(d => d.Pet)
                    .WithMany(p => p.PaymentRecord)
                    .HasForeignKey(d => d.PetId)
                    .HasConstraintName("FK_PaymentRecord_Pet");
            });

            modelBuilder.Entity<Pet>(entity =>
            {
                entity.Property(e => e.PetId).HasColumnName("PetID");

                entity.Property(e => e.BirthDay)
                    .HasColumnType("date")
                    .HasComment("生日");

                entity.Property(e => e.Breed)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasComment("品種");

                entity.Property(e => e.CreateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.CreateUser)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.Gender)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasComment("性別");

                entity.Property(e => e.ModifyTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ModifyUser)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.NormalPrice)
                    .HasColumnType("money")
                    .HasComment("單次價格");

                entity.Property(e => e.PetName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasComment("名字");

                entity.Property(e => e.SubscriptionPrice)
                    .HasColumnType("money")
                    .HasComment("包月價格");
            });

            modelBuilder.Entity<PetRelation>(entity =>
            {
                entity.Property(e => e.PetRelationId).HasColumnName("PetRelationID");

                entity.Property(e => e.ContactPersonId).HasColumnName("ContactPersonID");

                entity.Property(e => e.CreateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.CreateUser)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.ModifyTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ModifyUser)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.PetId).HasColumnName("PetID");

                entity.HasOne(d => d.ContactPerson)
                    .WithMany(p => p.PetRelation)
                    .HasForeignKey(d => d.ContactPersonId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PetRelation_ContactPerson");

                entity.HasOne(d => d.Pet)
                    .WithMany(p => p.PetRelation)
                    .HasForeignKey(d => d.PetId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PetRelation_Pet");
            });

            modelBuilder.Entity<ReserveRecord>(entity =>
            {
                entity.Property(e => e.ReserveRecordId).HasColumnName("ReserveRecordID");

                entity.Property(e => e.CreateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.CreateUser)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.Memo)
                    .IsRequired()
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.ModifyTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ModifyUser)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.PetId).HasColumnName("PetID");

                entity.Property(e => e.ReserverDate)
                    .HasColumnType("date")
                    .HasColumnName("ReserverDate ");

                entity.Property(e => e.ReserverTime).HasColumnName("ReserverTime ");

                entity.Property(e => e.SubscriptionId).HasColumnName("SubscriptionID");

                entity.HasOne(d => d.Subscription)
                    .WithMany(p => p.ReserveRecord)
                    .HasForeignKey(d => d.SubscriptionId)
                    .HasConstraintName("FK_ReserveRecord_Pet");
            });

            modelBuilder.Entity<Scrole>(entity =>
            {
                entity.HasKey(e => e.RoleId)
                    .HasName("PK__SCRole__8AFACE3A6F25AC8C");

                entity.ToTable("SCRole");

                entity.Property(e => e.RoleId).HasColumnName("RoleID");

                entity.Property(e => e.RoleName)
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Scuser>(entity =>
            {
                entity.ToTable("SCUser");

                entity.Property(e => e.ScuserId).HasColumnName("SCUserID");

                entity.Property(e => e.CreateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.CreateUser)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.LastLogin).HasColumnType("datetime");

                entity.Property(e => e.ModifyTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ModifyUser)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.PasswordHash)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.UserName).HasMaxLength(20);
            });

            modelBuilder.Entity<Subscription>(entity =>
            {
                entity.Property(e => e.SubscriptionId).HasColumnName("SubscriptionID");

                entity.Property(e => e.CreateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.CreateUser)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.EndDate).HasColumnType("date");

                entity.Property(e => e.ModifyTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ModifyUser)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.PetId).HasColumnName("PetID");

                entity.Property(e => e.StartDate).HasColumnType("date");

                entity.Property(e => e.SubscriptionDate).HasColumnType("date");

                entity.HasOne(d => d.Pet)
                    .WithMany(p => p.Subscription)
                    .HasForeignKey(d => d.PetId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Subscription_Pet");
            });

            modelBuilder.Entity<SystemCode>(entity =>
            {
                entity.HasKey(e => e.CodeId)
                    .HasName("PK__SystemCo__C6DE2C358B5ECB32");

                entity.HasIndex(e => new { e.CodeType, e.Code }, "UQ_CodeType")
                    .IsUnique();

                entity.Property(e => e.CodeId).HasColumnName("CodeID");

                entity.Property(e => e.Code)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.CodeType)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.CreateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.CreateUser)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.Description)
                    .HasMaxLength(200)
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.EndDate).HasColumnType("date");

                entity.Property(e => e.ModifyTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ModifyUser)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.Sort).HasDefaultValueSql("((0))");

                entity.Property(e => e.StartDate)
                    .HasColumnType("date")
                    .HasDefaultValueSql("(getdate())");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}