// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSalon.Models.EntityModels
{
    public partial class ReserveRecord
    {
        public long ReserveRecordId { get; set; }
        public long PetId { get; set; }
        public long? SubscriptionId { get; set; }
        public DateTime ReserverDate { get; set; }
        public TimeSpan ReserverTime { get; set; }
        public string Memo { get; set; }
        public string CreateUser { get; set; }
        public DateTime CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public DateTime ModifyTime { get; set; }

        public virtual Subscription Subscription { get; set; }
    }
}