// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSalon.Models.EntityModels
{
    public partial class ReserveRecord
    {
        public ReserveRecord()
        {
            PaymentRecord = new HashSet<PaymentRecord>();
        }

        public long ReserveRecordId { get; set; }
        public long PetId { get; set; }
        public long? SubscriptionId { get; set; }
        public DateTime ReserverDate { get; set; }
        public TimeSpan ReserverTime { get; set; }
        public string Status { get; set; }
        public decimal TotalAmount { get; set; }
        public bool UseSubscription { get; set; }
        public string ServiceType { get; set; }
        public int SubscriptionDeductionCount { get; set; }
        public string Memo { get; set; }
        public string CreateUser { get; set; }
        public DateTime CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public DateTime ModifyTime { get; set; }

        public virtual Pet Pet { get; set; }
        public virtual Subscription Subscription { get; set; }
        public virtual ICollection<PaymentRecord> PaymentRecord { get; set; }
    }
}