// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSalon.Models.EntityModels
{
    public partial class Subscription
    {
        public Subscription()
        {
            ReserveRecord = new HashSet<ReserveRecord>();
        }

        public long SubscriptionId { get; set; }
        public long PetId { get; set; }
        public DateTime SubscriptionDate { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string CreateUser { get; set; }
        public DateTime CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public DateTime ModifyTime { get; set; }

        public virtual Pet Pet { get; set; }
        public virtual ICollection<ReserveRecord> ReserveRecord { get; set; }
    }
}