// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSalon.Models.EntityModels
{
    public partial class SubscriptionType
    {
        public SubscriptionType()
        {
            Subscription = new HashSet<Subscription>();
        }

        public long SubscriptionTypeId { get; set; }
        public string TypeCode { get; set; }
        public string TypeName { get; set; }
        public int DefaultUsageLimit { get; set; }
        public decimal DefaultPrice { get; set; }
        public string AvailableServiceTypes { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public int SortOrder { get; set; }
        public string CreateUser { get; set; }
        public DateTime CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public DateTime ModifyTime { get; set; }

        public virtual ICollection<Subscription> Subscription { get; set; }
    }
}