/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactForm: typeof import('./src/components/forms/ContactForm.vue')['default']
    IncomeForm: typeof import('./src/components/forms/IncomeForm.vue')['default']
    PetContactsManager: typeof import('./src/components/forms/PetContactsManager.vue')['default']
    PetForm: typeof import('./src/components/forms/PetForm.vue')['default']
    ReservationForm: typeof import('./src/components/forms/ReservationForm.vue')['default']
    RoleForm: typeof import('./src/components/forms/RoleForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubscriptionDashboard: typeof import('./src/components/SubscriptionDashboard.vue')['default']
    SubscriptionForm: typeof import('./src/components/forms/SubscriptionForm.vue')['default']
    SubscriptionManager: typeof import('./src/components/forms/SubscriptionManager.vue')['default']
    SystemCodeSelect: typeof import('./src/components/common/SystemCodeSelect.vue')['default']
    UserPermissionsDialog: typeof import('./src/components/dialogs/UserPermissionsDialog.vue')['default']
    UserRoleAssignForm: typeof import('./src/components/forms/UserRoleAssignForm.vue')['default']
  }
}
