namespace PetSalon.Models.DTOs
{
    public class IncomeCreateDto
    {
        public long? ReserveRecordId { get; set; }
        public string IncomeType { get; set; }
        public decimal Amount { get; set; }
        public DateTime IncomeDate { get; set; }
        public string Description { get; set; }
        public bool IsAutoGenerated { get; set; } = false;
    }

    public class IncomeUpdateDto
    {
        public long IncomeId { get; set; }
        public string IncomeType { get; set; }
        public decimal Amount { get; set; }
        public DateTime IncomeDate { get; set; }
        public string Description { get; set; }
    }

    public class IncomeDetailsDto
    {
        public long IncomeId { get; set; }
        public long? ReserveRecordId { get; set; }
        public string PetName { get; set; }
        public string ContactName { get; set; }
        public string IncomeType { get; set; }
        public string IncomeTypeName { get; set; }
        public decimal Amount { get; set; }
        public DateTime IncomeDate { get; set; }
        public string Description { get; set; }
        public bool IsAutoGenerated { get; set; }
        public DateTime CreateTime { get; set; }
        public List<string> ServiceNames { get; set; } = new List<string>();
    }

    public class ExpenseCreateDto
    {
        public string ExpenseType { get; set; }
        public decimal Amount { get; set; }
        public DateTime ExpenseDate { get; set; }
        public string Description { get; set; }
        public string Receipt { get; set; }
    }

    public class ExpenseUpdateDto
    {
        public long ExpenseId { get; set; }
        public string ExpenseType { get; set; }
        public decimal Amount { get; set; }
        public DateTime ExpenseDate { get; set; }
        public string Description { get; set; }
        public string Receipt { get; set; }
    }

    public class ExpenseDetailsDto
    {
        public long ExpenseId { get; set; }
        public string ExpenseType { get; set; }
        public string ExpenseTypeName { get; set; }
        public decimal Amount { get; set; }
        public DateTime ExpenseDate { get; set; }
        public string Description { get; set; }
        public string Receipt { get; set; }
        public DateTime CreateTime { get; set; }
    }

    public class FinancialSummaryDto
    {
        public DateTime PeriodStart { get; set; }
        public DateTime PeriodEnd { get; set; }
        public decimal TotalIncome { get; set; }
        public decimal TotalExpense { get; set; }
        public decimal NetProfit => TotalIncome - TotalExpense;
        public decimal ProfitMargin => TotalIncome > 0 ? (NetProfit / TotalIncome) * 100 : 0;
        
        public List<IncomeByTypeDto> IncomeByType { get; set; } = new List<IncomeByTypeDto>();
        public List<ExpenseByTypeDto> ExpenseByType { get; set; } = new List<ExpenseByTypeDto>();
        
        public int TotalReservations { get; set; }
        public decimal AverageReservationValue => TotalReservations > 0 ? TotalIncome / TotalReservations : 0;
    }

    public class IncomeByTypeDto
    {
        public string IncomeType { get; set; }
        public string IncomeTypeName { get; set; }
        public decimal Amount { get; set; }
        public int Count { get; set; }
        public decimal Percentage { get; set; }
    }

    public class ExpenseByTypeDto
    {
        public string ExpenseType { get; set; }
        public string ExpenseTypeName { get; set; }
        public decimal Amount { get; set; }
        public int Count { get; set; }
        public decimal Percentage { get; set; }
    }

    public class DailyFinancialDto
    {
        public DateTime Date { get; set; }
        public decimal Income { get; set; }
        public decimal Expense { get; set; }
        public decimal Net => Income - Expense;
        public int ReservationCount { get; set; }
    }

    public class MonthlyFinancialDto
    {
        public int Year { get; set; }
        public int Month { get; set; }
        public string MonthName { get; set; }
        public decimal Income { get; set; }
        public decimal Expense { get; set; }
        public decimal Net => Income - Expense;
        public int ReservationCount { get; set; }
        public int WorkingDays { get; set; }
        public decimal AverageDailyIncome => WorkingDays > 0 ? Income / WorkingDays : 0;
    }
}